### PR TITLE
Added toast feedback to navDrawer. Adapter notifies drawerfragment of…

### PR DESCRIPTION
**Pull request by t1miller**
… the update. The drawer fragment wont do anything with this until it the drawer closes.

### CODE REVIEW

**Comment by AdamDorwart** [comment]
I just tried it out. When they pop up looks correct, but the actual messages need some work. For instance, "Sorting by RATING for" is not a complete sentence and has weird formatting. Add some strings to strings.xml for the different options so we can change them easily in the future.

**Comment by AdamDorwart** [comment]
Code looks clean though

**Comment by t1miller** [comment]
Let me know what we want the feedback to say and I can implement it. Its kind of weird to do with multiple days. Maybe David and Chloe can give some input too.

**Comment by AdamDorwart** [comment]
Hey I don't think I was clear with the spec for this. I didn't intend on it showing "Sorted by rating" and "Showing Today's deals" together into one Toast. It should only show you what you just changed. So if i change the sorting from rating to proximity, it just says "Sorted by proximity". And then when I switch from today to Monday it says "Showing Today's deals". When you perform both actions it can just show separate Toasts.

**Comment by AdamDorwart** [comment]
So if you tap Proximity once it closes the nav drawer and displays the correct message. However, if you open the drawer and pressed the (already selected) proximity button again, the drawer closes and says "Showing Today's deals"

**Comment by patelanjali** [comment]
Also, I see that when u select tuesday or any other day, it always says Today's deal on the deal list screen. I think we need to fix that.

**Comment by t1miller** [comment]
Yeah we haven't added that in when we did the new nav drawer. Make it an issue.

**Pull request merged**
